# Generated by Django 5.2.17 on 2026-10-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_policy_categories'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moderationcase',
            new_name='moderation__status_8eaa85_idx',
            old_name='moderation__status_051d9c_idx',
        ),
        migrations.RenameIndex(
            model_name='moderationcase',
            new_name='moderation__sender__91ab27_idx',
            old_name='moderation__sender_2f4d24_idx',
        ),
    ]
