from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[("chat","0005_localgram_v6"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="AttachmentScanJob",fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("status",models.CharField(choices=[("queued","В очереди"),("processing","Обработка"),("done","Готово"),("error","Ошибка")],db_index=True,default="queued",max_length=12)),("attempts",models.PositiveSmallIntegerField(default=0)),("last_error",models.TextField(blank=True)),("queued_at",models.DateTimeField(auto_now_add=True,db_index=True)),("started_at",models.DateTimeField(blank=True,null=True)),("finished_at",models.DateTimeField(blank=True,null=True)),("updated_at",models.DateTimeField(auto_now=True)),("attachment",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="security_job",to="chat.attachment")),],options={"ordering":["queued_at"]}),
        migrations.CreateModel(name="DLPCase",fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("source",models.CharField(choices=[("message","Сообщение"),("attachment","Вложение")],db_index=True,max_length=16)),("severity",models.CharField(choices=[("low","Низкий"),("medium","Средний"),("high","Высокий"),("critical","Критический")],db_index=True,default="medium",max_length=12)),("status",models.CharField(choices=[("open","Открыт"),("reviewed","Проверен"),("dismissed","Ложное срабатывание")],db_index=True,default="open",max_length=12)),("rule",models.CharField(db_index=True,max_length=80)),("matches",models.JSONField(blank=True,default=list)),("excerpt",models.TextField(blank=True)),("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),("reviewed_at",models.DateTimeField(blank=True,null=True)),("reviewer_note",models.TextField(blank=True)),("attachment",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="dlp_cases",to="chat.attachment")),("conversation",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="dlp_cases",to="chat.conversation")),("message",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="dlp_cases",to="chat.message")),("reviewed_by",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="dlp_reviews",to=settings.AUTH_USER_MODEL)),("sender",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="dlp_cases",to=settings.AUTH_USER_MODEL)),],options={"ordering":["-created_at"],"indexes":[models.Index(fields=["status","severity","created_at"],name="securitycen_status_6e68a7_idx")]}),
        migrations.CreateModel(name="SecurityIncident",fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("kind",models.CharField(choices=[("malware","Malware"),("auth","Authentication"),("device","Device"),("dlp","DLP"),("moderation","Moderation")],db_index=True,max_length=16)),("severity",models.CharField(db_index=True,default="medium",max_length=12)),("title",models.CharField(max_length=180)),("details",models.JSONField(blank=True,default=dict)),("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),("resolved_at",models.DateTimeField(blank=True,null=True)),("user",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="security_incidents",to=settings.AUTH_USER_MODEL)),],options={"ordering":["-created_at"]}),
    ]
