# Generated by Django 5.2.17 on 2026-10-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securitycenter', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dlpcase',
            new_name='securitycen_status_cd880e_idx',
            old_name='securitycen_status_6e68a7_idx',
        ),
    ]
