# Generated by Django 5.2.17 on 2026-10-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_artel_link_v13_8_6_presence_lifecycle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ratelimitevent',
            new_name='operations__categor_fbe327_idx',
            old_name='operations__categor_26fe7a_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitevent',
            new_name='operations__user_id_d86427_idx',
            old_name='operations__user_id_a6c990_idx',
        ),
    ]
