$ErrorActionPreference = "Continue"
Write-Host "=== Localgram v7 Doctor ===" -ForegroundColor Cyan
function Section($n,$title){ Write-Host ""; Write-Host "[$n/18] $title" -ForegroundColor Yellow }
Section 1 "Docker Compose services"; docker compose ps -a
Section 2 "Django system check"; docker compose exec web python manage.py check
Section 3 "Accounts migrations"; docker compose exec web python manage.py showmigrations accounts
Section 4 "Chat migrations"; docker compose exec web python manage.py showmigrations chat
Section 5 "Moderation migrations"; docker compose exec web python manage.py showmigrations moderation
Section 6 "Security Center migrations"; docker compose exec web python manage.py showmigrations securitycenter
Section 7 "Operations migrations"; docker compose exec web python manage.py showmigrations operations
Section 8 "Health / PostgreSQL / Redis"; try { Invoke-RestMethod -Uri "http://127.0.0.1:8000/healthz/" -TimeoutSec 10 | ConvertTo-Json } catch { Write-Host $_ -ForegroundColor Red }
Section 9 "Core counters"; docker compose exec web python manage.py shell -c "from apps.accounts.models import User; from apps.chat.models import Conversation,Message,Attachment; print({'users':User.objects.count(),'chats':Conversation.objects.count(),'messages':Message.objects.count(),'attachments':Attachment.objects.count()})"
Section 10 "RBAC / device trust"; docker compose exec web python manage.py shell -c "from apps.accounts.models import User,RoleProfile,DeviceSession; print({'developer':list(User.objects.filter(role='developer').values_list('email',flat=True)),'custom_roles':RoleProfile.objects.count(),'trusted':DeviceSession.objects.filter(trust_status='trusted',revoked_at__isnull=True).count(),'suspicious':DeviceSession.objects.filter(trust_status__in=['suspicious','blocked'],revoked_at__isnull=True).count()})"
Section 11 "MinIO storage"; docker compose exec web python manage.py shell -c "from django.conf import settings; from django.core.files.storage import default_storage; print({'s3_enabled':settings.USE_S3_STORAGE,'storage':default_storage.__class__.__name__,'bucket':getattr(settings,'AWS_STORAGE_BUCKET_NAME','local'),'probe':default_storage.exists('__localgram_doctor_missing__') is False})"
Section 12 "ClamAV"; docker compose exec web python manage.py shell -c "import clamd; from django.conf import settings; c=clamd.ClamdNetworkSocket(settings.CLAMAV_HOST,settings.CLAMAV_PORT,timeout=8); print({'clamav':c.ping(),'version':c.version()})"
Section 13 "Workers / queues"; docker compose exec web python manage.py shell -c "from django.core.cache import cache; from apps.moderation.models import ModerationScanJob; from apps.securitycenter.models import AttachmentScanJob; print({'moderator':bool(cache.get('localgram:moderation_worker:alive')),'security':bool(cache.get('localgram:security_worker:alive')),'scheduler':bool(cache.get('localgram:scheduler_worker:alive')),'moderation_queue':ModerationScanJob.objects.filter(status__in=['queued','processing']).count(),'security_queue':AttachmentScanJob.objects.filter(status__in=['queued','processing']).count()})"
Section 14 "Polls / scheduled posts"; docker compose exec web python manage.py shell -c "from apps.chat.models import Poll,ScheduledPost; print({'polls':Poll.objects.count(),'scheduled_pending':ScheduledPost.objects.filter(status='scheduled').count(),'scheduled_errors':ScheduledPost.objects.filter(status='error').count()})"
Section 15 "Security / anti-spam"; docker compose exec web python manage.py shell -c "from datetime import timedelta; from django.utils import timezone; from apps.operations.models import RateLimitEvent; from apps.securitycenter.models import DLPCase; print({'rate_limit_24h':RateLimitEvent.objects.filter(created_at__gte=timezone.now()-timedelta(hours=24)).count(),'dlp_open':DLPCase.objects.filter(status='open').count()})"
Section 16 "Backup restore verification / client policies"; docker compose exec web python manage.py shell -c "from apps.operations.models import BackupVerification,ClientVersionPolicy; print({'last_restore':list(BackupVerification.objects.values('status','started_at')[:1]),'client_policies':list(ClientVersionPolicy.objects.values_list('platform','latest_version','minimum_version'))})"
Section 17 "Prometheus package / operational JSON"; docker compose exec web python manage.py shell -c "import prometheus_client; from apps.operations.management.commands.localgram_status import Command; print({'prometheus':'import_ok','operations':'ok'})"
Section 18 "Last logs"; Write-Host "--- web ---"; docker compose logs --tail=60 web; Write-Host "--- moderator ---"; docker compose logs --tail=40 moderator; Write-Host "--- securityworker ---"; docker compose logs --tail=40 securityworker; Write-Host "--- scheduler ---"; docker compose logs --tail=40 scheduler; Write-Host "--- clamav ---"; docker compose logs --tail=20 clamav; Write-Host "--- minio ---"; docker compose logs --tail=20 minio
Write-Host ""; Write-Host "=== Localgram v7 Doctor finished ===" -ForegroundColor Cyan
