# Generated by Django 5.2.17 on 2026-10-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_action_0c0ad1_idx',
            old_name='audit_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_object__4aa284_idx',
            old_name='audit_object_created_idx',
        ),
    ]
