from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies=[("chat","0004_localgram_v4"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.AlterField(model_name="conversation",name="kind",field=models.CharField(choices=[("direct","Личный чат"),("group","Группа"),("channel","Канал"),("saved","Сохранённые сообщения")],default="direct",max_length=10)),
        migrations.AlterField(model_name="message",name="kind",field=models.CharField(choices=[("text","Текст"),("file","Файл"),("voice","Голосовое"),("system","Системное"),("sticker","Стикер")],default="text",max_length=12)),
        migrations.AddField(model_name="message",name="client_message_id",field=models.CharField(blank=True,db_index=True,max_length=64)),
        migrations.AddField(model_name="attachment",name="scan_status",field=models.CharField(db_index=True,default="safe",max_length=16),preserve_default=False),
        migrations.AlterField(model_name="attachment",name="scan_status",field=models.CharField(db_index=True,default="pending",max_length=16)),
        migrations.AddField(model_name="attachment",name="scan_engine",field=models.CharField(blank=True,max_length=64)),
        migrations.AddField(model_name="attachment",name="scan_signature",field=models.CharField(blank=True,max_length=255)),
        migrations.AddField(model_name="attachment",name="scanned_at",field=models.DateTimeField(blank=True,null=True)),
        migrations.CreateModel(name="MessageMention",fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("is_all",models.BooleanField(default=False)),("created_at",models.DateTimeField(auto_now_add=True)),
            ("message",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="mentions",to="chat.message")),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="message_mentions",to=settings.AUTH_USER_MODEL)),],
            options={"constraints":[models.UniqueConstraint(fields=("message","user"),name="unique_message_mention")]},),
        migrations.CreateModel(name="UserNotification",fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("kind",models.CharField(choices=[("mention","Упоминание"),("reply","Ответ"),("reaction","Реакция"),("system","Системное")],db_index=True,default="system",max_length=16)),("title",models.CharField(blank=True,max_length=180)),("body",models.CharField(blank=True,max_length=500)),("read_at",models.DateTimeField(blank=True,db_index=True,null=True)),("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),
            ("actor",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="notification_actions",to=settings.AUTH_USER_MODEL)),("message",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE,related_name="notifications",to="chat.message")),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="notifications",to=settings.AUTH_USER_MODEL)),],options={"ordering":["-created_at"]}),
        migrations.CreateModel(name="MessageReceipt",fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("delivered_at",models.DateTimeField(blank=True,db_index=True,null=True)),("read_at",models.DateTimeField(blank=True,db_index=True,null=True)),("message",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="receipts",to="chat.message")),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="message_receipts",to=settings.AUTH_USER_MODEL)),],options={"constraints":[models.UniqueConstraint(fields=("message","user"),name="unique_message_receipt")],"indexes":[models.Index(fields=["user","read_at"],name="chat_messag_user_id_9bd2de_idx")]}),
        migrations.CreateModel(name="MessagePin",fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("created_at",models.DateTimeField(auto_now_add=True)),("conversation",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="pins",to="chat.conversation")),("message",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="pin_records",to="chat.message")),("pinned_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="message_pins",to=settings.AUTH_USER_MODEL)),],options={"ordering":["-created_at"],"constraints":[models.UniqueConstraint(fields=("conversation","message"),name="unique_conversation_message_pin")]}),
        migrations.CreateModel(name="ChatFolder",fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=40)),("smart_type",models.CharField(choices=[("custom","Пользовательская"),("all","Все"),("direct","Личные"),("groups","Группы"),("channels","Каналы"),("unread","Непрочитанные"),("archived","Архив")],default="custom",max_length=16)),("position",models.PositiveSmallIntegerField(default=0)),("include_muted",models.BooleanField(default=True)),("created_at",models.DateTimeField(auto_now_add=True)),("user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="chat_folders",to=settings.AUTH_USER_MODEL)),],options={"ordering":["position","id"]}),
        migrations.CreateModel(name="ChatFolderConversation",fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("conversation",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="folder_links",to="chat.conversation")),("folder",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="chat_links",to="chat.chatfolder")),],options={"constraints":[models.UniqueConstraint(fields=("folder","conversation"),name="unique_folder_conversation")]}),
        migrations.CreateModel(name="StickerPack",fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=80)),("slug",models.SlugField(max_length=80,unique=True)),("active",models.BooleanField(default=True)),("created_at",models.DateTimeField(auto_now_add=True)),("created_by",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="sticker_packs",to=settings.AUTH_USER_MODEL)),]),
        migrations.CreateModel(name="Sticker",fields=[
            ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("emoji",models.CharField(blank=True,max_length=16)),("title",models.CharField(blank=True,max_length=80)),("image",models.ImageField(upload_to="stickers/%Y/%m/")),("is_custom_emoji",models.BooleanField(default=False)),("active",models.BooleanField(default=True)),("position",models.PositiveSmallIntegerField(default=0)),("pack",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="stickers",to="chat.stickerpack")),],options={"ordering":["position","id"]}),
        migrations.AddField(model_name="message",name="sticker",field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="messages",to="chat.sticker")),
        migrations.AddConstraint(model_name="message",constraint=models.UniqueConstraint(condition=~models.Q(client_message_id=""),fields=("sender","client_message_id"),name="unique_sender_client_message_id")),
    ]
