# Generated by Django 5.2.17 on 2026-10-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_rmes_v15_call_records'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='callrecord',
            new_name='chat_callre_status_a577a9_idx',
            old_name='chat_callre_status_313f13_idx',
        ),
        migrations.RenameIndex(
            model_name='callrecord',
            new_name='chat_callre_caller__7c08b1_idx',
            old_name='chat_callre_caller__cf8b09_idx',
        ),
        migrations.RenameIndex(
            model_name='callrecord',
            new_name='chat_callre_callee__8e529e_idx',
            old_name='chat_callre_callee__785286_idx',
        ),
        migrations.RenameIndex(
            model_name='callsignalevent',
            new_name='chat_callsi_recipie_c8fd41_idx',
            old_name='chat_callsi_recipie_585011_idx',
        ),
        migrations.RenameIndex(
            model_name='callsignalevent',
            new_name='chat_callsi_call_id_51a86b_idx',
            old_name='chat_callsi_call_id_b67e24_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_3154fc_idx',
            old_name='chat_messag_convers_82f431_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereceipt',
            new_name='chat_messag_user_id_8ceef9_idx',
            old_name='chat_messag_user_id_9bd2de_idx',
        ),
    ]
